### PR TITLE
fix fix rand_crop

### PR DESCRIPTION
**Pull request by superzrx**
remove duplicate roi

### CODE REVIEW

**Comment by antinucleon** [comment]
I tested in NDSB, it is still not correct. We should fix it together.

**Comment by antinucleon** [comment]
I think we need to imwrite to see what happened inside. In the NDSB test, train acc is much higher than test acc only after 5 epoch, so I think there is something wrong in augment

**Comment by superzrx** [comment]
@antinucleon OK, I`ll test it on ImageNet.

**Comment by antinucleon** [comment]
@superzrx Thank you.

**Comment by antinucleon** [comment]
From the code I think it is correct. For NDSB abnormal training curve, maybe the problem is from batch norm but not augmentation. I am going to run imwrite experiment after I settle down in a cafe (I am still traveling). Let's fully check it then please open a new PR. I am sorry for that.

**Comment by superzrx** [comment]
@antinucleon ok

**Comment by superzrx** [comment]
@antinucleon 
test passed on kaiming.conf
image

**Pull request merged**
