### PR TITLE
new windows version

### PR DESCRIPTION
**Pull request by terrychenism**
1. remove zlib dependency
2. provide 3rdparty(cudnn/openblas) download link
3. build with lastest version

### CODE REVIEW

**Comment by antinucleon** [comment]
Thanks for the PR. I have done similar work in dev branch. For windows support, I think we can provide a guide but not including 3rd dropbox link. I will check it today.

**Comment by tqchen** [comment]
Seems lots of files in example have been mistakenly removed. It might be easier to start from a clean fork and add the projects. 

Thanks!

**Comment by antinucleon** [comment]
We have provided a Visual Studio project to build only with OpenBLAS and OpenCV. This project contains im2bin, cxxnet and cxxnet_wrapper.dll.

**Comment by happynear** [comment]
I suggest to add srand() to random.h, because the rand() in windows have no parameters and would always start from 1.
Change like this:
inline void Seed(unsigned seed) {
    this->rseed_ = seed;
	#if _MSC_VER
	srand(seed);
	#endif
  }

**Comment by tqchen** [comment]
nice catch, thanks

**Comment by antinucleon** [comment]
Thanks @happynear ! I don't use Windows for years, I will change it!

**Pull request closed without merging**
